# Generated by Django 2.2.4 on 2019-10-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='It',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_last', models.CharField(max_length=30)),
                ('ip_first', models.CharField(max_length=30)),
                ('ip_MRN', models.IntegerField()),
                ('ip_cg', models.IntegerField()),
                ('ip_tg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_last', models.CharField(max_length=30)),
                ('p_first', models.CharField(max_length=30)),
                ('p_MRN', models.IntegerField()),
                ('p_cg', models.IntegerField()),
                ('p_tg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nurses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_last', models.CharField(max_length=30)),
                ('n_first', models.CharField(max_length=30)),
                ('n_UNIT', models.IntegerField()),
            ],
        ),
    ]
