# Generated by Django 2.2.4 on 2019-10-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_first', models.CharField(max_length=30)),
                ('contact_last', models.CharField(max_length=30)),
                ('contact_PHONE', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_first', models.CharField(max_length=30)),
                ('doc_last', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first', models.CharField(max_length=30)),
                ('patient_last', models.CharField(max_length=30)),
                ('ethnicity', models.CharField(max_length=30)),
                ('AGE', models.IntegerField()),
            ],
        ),
    ]
